import Header from "@/components/Header";
import Footer from "@/components/Footer";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold text-foreground mb-2">DOSE Academy — Privacy Policy</h1>
        <p className="text-muted-foreground mb-1">Last updated: April 3, 2026</p>
        <p className="text-muted-foreground mb-10">DOSE/ODISHON Corp. | <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a></p>

        <div className="space-y-10 text-foreground">
          <section>
            <p className="text-muted-foreground leading-relaxed mb-4">DOSE Academy is a product of DOSE/ODISHON Corp. ("we," "our," or "us"). We are deeply committed to protecting the privacy of the adolescents who use our platform. This Privacy Policy explains what information we collect, how we use it, who we share it with, and the rights that parents, guardians, and authorized institutional partners have regarding that information.</p>
            <p className="text-muted-foreground leading-relaxed mb-4">DOSE Academy is designed for use by adolescents ages 10–17 ("Adolescent Users") under the supervision of a parent, legal guardian, school, or licensed provider ("Authorized Adult" or "Partner Organization"). All accounts must be created or approved by an Authorized Adult. Adolescent Users may not register independently.</p>
            <p className="text-muted-foreground leading-relaxed"><strong className="text-foreground">Important:</strong> DOSE Academy is not a medical or clinical service. It is a cognitive support tool designed to complement — not replace — professional mental health care. If an Adolescent User is experiencing a mental health crisis, please contact a licensed professional or call <strong className="text-foreground">988</strong> (Suicide & Crisis Lifeline) immediately.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">1. Scope of This Policy</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">This Privacy Policy applies to all Adolescent Users of DOSE Academy and to the Authorized Adults and Partner Organizations that manage their accounts. It covers data collected through the DOSE Academy mobile application and any related web-based services operated by DOSE/ODISHON Corp.</p>
            <p className="text-muted-foreground leading-relaxed">DOSE (the adult product) is governed by a separate Privacy Policy available at <a href="https://getdose.app" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">getdose.app</a>. If you are 18 or older and looking for the adult product policy, please refer to that document.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">2. Information We Collect</h2>

            <h3 className="text-xl font-medium mb-2 mt-6">2a. Information Provided by Authorized Adults or Partner Organizations</h3>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li><strong className="text-foreground">Account registration:</strong> name, email address, and password of the Authorized Adult or administrator</li>
              <li><strong className="text-foreground">Adolescent User profile:</strong> first name or preferred name, age range, and any optional diagnostic context voluntarily provided</li>
              <li><strong className="text-foreground">Payment information:</strong> billing name, address, and payment method — processed securely by a third-party payment processor; we do not store full card numbers</li>
              <li><strong className="text-foreground">Communications:</strong> messages sent to our support team</li>
            </ul>

            <h3 className="text-xl font-medium mb-2 mt-6">2b. Information Generated by Adolescent Users</h3>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li><strong className="text-foreground">Tool interactions:</strong> inputs and session data within DOSE Academy tools (SPARK, WAVE, RSD Junior, POPCORN, Squad Focus)</li>
              <li><strong className="text-foreground">Progress and engagement data:</strong> features accessed, session duration, and milestone completions</li>
              <li><strong className="text-foreground">Peer accountability content:</strong> messages or prompts shared within Squad Focus, visible only to members of the user's designated squad</li>
            </ul>

            <h3 className="text-xl font-medium mb-2 mt-6">2c. Information Collected Automatically</h3>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li><strong className="text-foreground">Device information:</strong> device type, operating system version, and app version</li>
              <li><strong className="text-foreground">Usage analytics:</strong> feature engagement patterns and session frequency</li>
              <li><strong className="text-foreground">Log data:</strong> timestamps, error reports, and anonymized IP addresses</li>
            </ul>

            <h3 className="text-xl font-medium mb-2 mt-6">2d. What We Do NOT Collect</h3>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li>We do not collect precise geolocation data</li>
              <li>We do not collect biometric data</li>
              <li>We do not serve third-party advertising or collect data for advertising purposes</li>
              <li>We do not use tracking technologies that follow users across third-party websites or apps</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">3. COPPA Compliance and Children Under 13</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">DOSE Academy complies with the Children's Online Privacy Protection Act (COPPA). For Adolescent Users under the age of 13, we require verifiable parental consent before collecting any personal information. We collect only the minimum information necessary to provide our services to users in this age group.</p>
            <h3 className="text-xl font-medium mb-2">Parental Rights for Users Under 13</h3>
            <p className="text-muted-foreground leading-relaxed mb-3">Parents and guardians of users under 13 have the right to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li>Review the personal information we have collected from their child</li>
              <li>Request correction of inaccurate information</li>
              <li>Request deletion of their child's personal information</li>
              <li>Refuse to permit further collection or use of their child's information</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">To exercise any of these rights, contact us at <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a>. We will respond to all verifiable requests within 30 days.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">4. How We Use Information</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">We use the information we collect to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li>Provide, operate, and improve DOSE Academy services</li>
              <li>Personalize the Adolescent User's in-app experience</li>
              <li>Track progress and deliver age-appropriate content and feedback</li>
              <li>Enable supervised peer accountability features within Squad Focus</li>
              <li>Process payments and manage subscriptions or institutional licenses</li>
              <li>Send service-related communications to Authorized Adults (account updates, security alerts)</li>
              <li>Analyze aggregate usage patterns to improve product features and clinical effectiveness</li>
              <li>Comply with applicable legal obligations</li>
              <li>Detect, prevent, and address fraud, abuse, or security incidents</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">We do not use Adolescent User data to train external AI models or sell it to third parties for any purpose.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">5. How We Share Information</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">We do not sell personal information. We may share information only in the following circumstances:</p>

            <h3 className="text-xl font-medium mb-2">5a. Service Providers</h3>
            <p className="text-muted-foreground leading-relaxed mb-4">We work with third-party vendors for hosting, analytics, payment processing, and customer support. These vendors process data on our behalf under written data processing agreements and are prohibited from using the data for any purpose other than providing services to us.</p>

            <h3 className="text-xl font-medium mb-2">5b. Partner Organizations</h3>
            <p className="text-muted-foreground leading-relaxed mb-4">If an Adolescent User is enrolled through a school, healthcare provider, or other licensed Partner Organization, that organization's authorized administrators may have access to the user's progress data and session summaries, consistent with the terms of our partner agreement and applicable law (including FERPA where applicable).</p>

            <h3 className="text-xl font-medium mb-2">5c. Authorized Adults</h3>
            <p className="text-muted-foreground leading-relaxed mb-4">Parents and guardians who create or manage an Adolescent User's account have access to progress reports and summary data for that user.</p>

            <h3 className="text-xl font-medium mb-2">5d. Legal Requirements</h3>
            <p className="text-muted-foreground leading-relaxed mb-4">We may disclose information when required by law, court order, or legal process, or when we reasonably believe disclosure is necessary to protect the rights, property, or safety of our users or the public.</p>

            <h3 className="text-xl font-medium mb-2">5e. Business Transfers</h3>
            <p className="text-muted-foreground leading-relaxed">In the event of a merger, acquisition, or sale of assets, user data may be transferred to the successor entity. We will provide notice to Authorized Adults before personal information of Adolescent Users is transferred and becomes subject to a different privacy policy.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">6. Data Retention</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">We retain personal information for as long as an account is active or as necessary to provide services. Authorized Adults may request deletion of an Adolescent User's account and all associated personal data at any time by contacting <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a>. We will process deletion requests within 30 days, subject to any legal retention obligations.</p>
            <p className="text-muted-foreground leading-relaxed">Aggregate, de-identified data that cannot reasonably be used to identify any individual may be retained indefinitely for research and product improvement purposes.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">7. Data Security</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">We implement industry-standard technical and organizational safeguards to protect personal information, including:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li>Encryption of data in transit using TLS</li>
              <li>Encryption of sensitive data at rest</li>
              <li>Access controls limiting data access to authorized personnel</li>
              <li>Regular security assessments and monitoring</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">No system is completely secure. In the event of a data breach affecting Adolescent User data, we will notify affected Authorized Adults and applicable regulatory authorities as required by law.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">8. Squad Focus and Peer Features</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">DOSE Academy's Squad Focus feature enables adolescents to participate in supervised peer accountability groups. The following data practices apply specifically to this feature:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li>Squad membership and interactions are visible only to members of the designated squad and authorized supervising adults</li>
              <li>Squad content is not publicly visible and is not shared with third parties</li>
              <li>Moderating adults or Partner Organization administrators may review squad activity to ensure appropriate use</li>
              <li>Users who engage in harassing, bullying, or harmful behavior within Squad Focus may have their access suspended</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4"><strong className="text-foreground">Important:</strong> Squad Focus is designed for constructive peer support only. DOSE Academy does not guarantee continuous human moderation of squad interactions. Authorized Adults are encouraged to review squad activity regularly.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">9. Institutional Partners: FERPA and HIPAA</h2>

            <h3 className="text-xl font-medium mb-2 mt-4">FERPA</h3>
            <p className="text-muted-foreground leading-relaxed mb-4">When DOSE Academy is deployed through a school or educational institution, student education records may be subject to the Family Educational Rights and Privacy Act (FERPA). In such cases, DOSE/ODISHON Corp. acts as a school official with a legitimate educational interest, and data is used solely for authorized educational purposes. Partner Organizations are responsible for ensuring appropriate consent is obtained in accordance with FERPA.</p>

            <h3 className="text-xl font-medium mb-2">HIPAA</h3>
            <p className="text-muted-foreground leading-relaxed">If a Partner Organization is a covered healthcare entity that shares protected health information (PHI) with DOSE Academy in connection with treatment, a Business Associate Agreement (BAA) may be required. Please contact us at <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a> to initiate this process before sharing any PHI.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">10. Cookies and Tracking Technologies</h2>
            <p className="text-muted-foreground leading-relaxed">DOSE Academy uses only essential cookies and session tokens necessary to operate the platform. We do not use third-party advertising cookies or cross-site tracking technologies. We do not serve behavioral advertising to Adolescent Users.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">11. Your Rights</h2>

            <h3 className="text-xl font-medium mb-2">Rights of Authorized Adults and Partner Organizations</h3>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li><strong className="text-foreground">Access:</strong> request a copy of the personal information we hold about an Adolescent User</li>
              <li><strong className="text-foreground">Correction:</strong> request correction of inaccurate or incomplete information</li>
              <li><strong className="text-foreground">Deletion:</strong> request deletion of an Adolescent User's account and personal data</li>
              <li><strong className="text-foreground">Portability:</strong> request a copy of data in a portable format</li>
              <li><strong className="text-foreground">Restriction:</strong> request that we limit processing of personal data in certain circumstances</li>
              <li><strong className="text-foreground">Withdrawal of consent:</strong> withdraw consent at any time where processing is based on consent</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">To exercise any of these rights, contact us at <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a>. We will verify your identity before processing requests and respond within 30 days.</p>

            <h3 className="text-xl font-medium mb-2 mt-6">California Residents</h3>
            <p className="text-muted-foreground leading-relaxed">If you are a California resident, you may have additional rights under the California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA), including the right to know, the right to delete, and the right to opt out of the sale of personal information. We do not sell personal information. To submit a request, contact us at <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a>.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">12. Changes to This Policy</h2>
            <p className="text-muted-foreground leading-relaxed">We may update this Privacy Policy from time to time. When we make material changes, we will notify Authorized Adults by email and/or in-app notification at least 14 days before the changes take effect, and will update the "Last updated" date at the top of this document. Your continued use of DOSE Academy after the effective date constitutes acceptance of the revised policy.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3">13. Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">If you have questions about this Privacy Policy, wish to exercise your rights, or need to report a privacy concern, please contact us:</p>
            <p className="text-muted-foreground leading-relaxed"><strong className="text-foreground">DOSE/ODISHON Corp.</strong><br />Email: <a href="mailto:support@getdose.app" className="text-primary hover:underline">support@getdose.app</a><br />Website: <a href="https://getdose.app" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">getdose.app</a></p>
            <p className="text-muted-foreground leading-relaxed mt-4">For parental rights requests regarding users under 13, please include "COPPA Request" in your subject line so we can prioritize your inquiry.</p>
          </section>

          <section className="border-t border-border pt-6">
            <p className="text-sm text-muted-foreground italic">This document was prepared for informational purposes. DOSE/ODISHON Corp. recommends that this policy be reviewed by qualified legal counsel before publication, particularly with respect to COPPA, FERPA, HIPAA, and applicable state privacy laws.</p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
